version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - .:/app
    env_file:
      - ".env"
    depends_on:
      - db
      - redis
    command: bash -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - WATCHFILES_FORCE_POLLING=true

  db:
    image: postgres:13
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis
    command: redis-server --requirepass password --appendonly yes --loglevel warning
    restart: unless-stopped
    ports:
      - "6377:6379"
    volumes:
      - redis_data:/var/lib/redis/data

volumes:
  postgres_data:
  redis_data:
