version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - ".env"
    depends_on:
      - db
    command: bash -c "uvicorn app:app --host 0.0.0.0 --port 8000 --reload"
  db:
    image: postgres:13
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
